/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lab01

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun String.isPalindrome(ignoreCase:Boolean, ignoreWhiteSpaces:Boolean): Boolean {
    var a:String = this
    var b:String = this
    if(ignoreCase && ignoreWhiteSpaces){
        return this.lowercase().filter { !it.isWhitespace() } == this.lowercase().reversed().filter {!it.isWhitespace()}

    }
    if(ignoreCase){
         return a.reversed().lowercase() == b.lowercase()
    }
//shall return true??
  return false
}
fun String.isPalindrome(ignoreCase:Boolean): Boolean {
    var a:String = this
    var b:String = this

    if(ignoreCase){
         return a.reversed().lowercase() == b.lowercase()
    }
//shall return true??
  return false
}
fun String.isPalindrome(): Boolean {
    if(this.lowercase().filter { !it.isWhitespace() }.length == 0){
        return false;
    }
    if(this.length == 1){
        return true
    }
    var a:String = this
    var b:String = this

  return a.reversed() == b
}
fun main() {
   println("saippuakauppias".isPalindrome()) // true
   println("abc".isPalindrome()) // false
   println("SaippuakauPPias".isPalindrome(ignoreCase = true)) // true
   println("Saippua kauPPias".isPalindrome(ignoreCase = true, ignoreWhiteSpaces = true)) // true
}
